<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Can not send email to ' => 'Nevar nosūtīt epastu uz',
  'MLLG_STATUS_ERROR' => 'Kļūda',
  'MLLG_STATUS_SENT' => 'Nosūtīs',
  'MLLG_TEXT_FORMAT_TEXT' => 'Teksts',
  'MLLG_TEXT_FORMAT_TEXTHTML' => 'HTML',
  'Mllg' => '',
  'Mllg Datetime' => 'Laiks',
  'Mllg Mailer Log' => '',
  'Mllg Mailer Logs' => '',
  'Mllg Model' => 'Modelis',
  'Mllg Model Name' => 'Modeļa nosaukums',
  'Mllg Status' => 'Status',
  'Mllg Subject' => 'Subject',
  'Mllg Text' => 'Teksts',
  'Mllg Text Format' => 'Formāts',
  'Mllg To' => 'Adresāts',
  'Mllg User' => 'Lietotājs',
  'user_full_name' => 'Lietotājs',  
);
